apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-dev
  namespace: develop
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_DB: anVsaWFvc2lzdGVt
  DB_ADDR: aHR0cDovLzE5Mi4xNjguNDkuMjozMDQzMgo=
  POSTGRES_PASSWORD: MGQwNjhCNDI5MEAxMjMK
  POSTGRES_USER: anVsaWFvc2lzdGVtZGV2Cg==
  POSTGRES_SCHEMA: cHVibGlj
  KEYCLOAK_PASSWORD: MTAyMEExMjM0NTY3OGI=
  KEYCLOAK_USER: anVsaWFvc2lzdGVtLWRldgo=
  KEYCLOAK_FRONTEND_URL: aHR0cHM6Ly9NeWtleWNsb2FrLWRldmVsb3BtZW50L2F1dGgvCg==
  PROXY_ADDRESS_FORWARDING: ZmFsc2UK
  KEYCLOAK_ADMIN_URL: aHR0cHM6Ly9NeWtleWNsb2FrLWRldmVsb3BtZW50L2F1dGgvcmVhbG1zL21hc3Rlci9hZG1pbi8K