# Servicio para PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: postgres-service-dev
  namespace: develop
  labels:
    app: postgres
spec:  
  ports:
  - name: postgres
    port: 5432
    nodePort: 30432  
  type: NodePort
  selector:
    app: postgres

---
# Deployment para PostgreSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment-dev
  namespace: develop
  labels:
    app: postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret-dev
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
            - mountPath: /docker-entrypoint-initdb.d
              name: init-script
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-claim-dev
        - name: init-script
          configMap:
            name: postgres-init-script-dev-configmap 

---
# Ingress para PostgreSQL
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postgres-ingress
  namespace: develop
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /postgres
            pathType: Prefix
            backend:
              service:
                name: postgres-service-dev
                port:
                  number: 5432
